/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket_hadi;

import java.awt.HeadlessException;
    import java.math.BigInteger;
    import java.security.MessageDigest;
    import java.sql.Connection;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Statement;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
import koneksi.koneksi_hadi;

/**
 *
 * @author admin
 */
public class FormLogin_hadi extends javax.swing.JFrame {
     private Connection koneksi;
     private koneksi_hadi db=new koneksi_hadi();    
    public boolean databaru;
    public String vpassword,vmd5;

    /**
     * Creates new form FormLogin_hadi
     */
    public FormLogin_hadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_hadi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password_hadi = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 100, 110);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Log In");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 120, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pass.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 270, 40, 40);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 286, 80, 16);
        getContentPane().add(user_hadi);
        user_hadi.setBounds(170, 192, 260, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 190, 40, 40);

        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 210, 80, 16);
        getContentPane().add(password_hadi);
        password_hadi.setBounds(170, 280, 260, 40);

        jButton1.setText("Exit");
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 370, 140, 40);

        jButton2.setText("Log in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 370, 140, 40);

        jLabel7.setFont(new java.awt.Font("Agency FB", 2, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cpright.png"))); // NOI18N
        jLabel7.setText("Muhamad Hadi Saputra - 021200015");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 470, 210, 48);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 160);

        setSize(new java.awt.Dimension(523, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
          db.koneksiDatabase();
            String query = "SELECT * FROM tbuser_hadi WHERE username ='"+ user_hadi.getText() +"' AND password=MD5('" + password_hadi.getText() + "')";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
         if (rs.next()) 
                {   
                   JOptionPane.showMessageDialog(null," Login Berhasil !");
                   FormMenu_hadi menu = new FormMenu_hadi();
                   menu.show();
                   dispose();
                } 
           else
                {
                   JOptionPane.showMessageDialog(null," Login Gagal, User atau Password Tidak Sama ! !");
                }
           } catch (SQLException | HeadlessException e)
       {
        
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin_hadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_hadi;
    private javax.swing.JTextField user_hadi;
    // End of variables declaration//GEN-END:variables
}
