/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket_hadi;
import java.awt.HeadlessException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi_hadi;

/**
 *
 * @author admin
 */
public class Formpegawai_hadi extends javax.swing.JFrame {
   private Connection koneksi;
   private koneksi_hadi db=new koneksi_hadi();    
   public boolean databaru;
   public String vpassword,vmd5;

    /**
     * Creates new form Formpegawai_hadi
     */
    public Formpegawai_hadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jekel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_pegawai_hadi = new javax.swing.JTextField();
        nama_pegawai_hadi = new javax.swing.JTextField();
        bagian_hadi = new javax.swing.JTextField();
        wanita_hadi = new javax.swing.JRadioButton();
        cari_hadi = new javax.swing.JTextField();
        pria_hadi = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        search = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        kontak_pegawai_hadi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_hadi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat_hadi = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 70, 70);

        jLabel2.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        jLabel2.setText("FORM PEGAWAI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 10, 190, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("ID PEGAWAI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 110, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("NAMA PEGAWAI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 110, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("JENIS KELAMIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 260, 110, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("ALAMAT PEGAWAI");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 330, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("BAGIAN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 430, 110, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("KONTAK PEGAWAI");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 490, 110, 30);
        getContentPane().add(id_pegawai_hadi);
        id_pegawai_hadi.setBounds(160, 100, 270, 40);
        getContentPane().add(nama_pegawai_hadi);
        nama_pegawai_hadi.setBounds(160, 180, 270, 40);
        getContentPane().add(bagian_hadi);
        bagian_hadi.setBounds(160, 420, 270, 40);

        jekel.add(wanita_hadi);
        wanita_hadi.setText("WANITA");
        getContentPane().add(wanita_hadi);
        wanita_hadi.setBounds(240, 260, 80, 25);
        getContentPane().add(cari_hadi);
        cari_hadi.setBounds(160, 620, 270, 40);

        jekel.add(pria_hadi);
        pria_hadi.setText("PRIA");
        getContentPane().add(pria_hadi);
        pria_hadi.setBounds(160, 260, 55, 25);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(620, 550, 110, 40);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seaRch.png"))); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(30, 620, 120, 40);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(140, 550, 100, 40);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(250, 550, 110, 40);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(370, 550, 110, 40);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(490, 550, 130, 40);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(30, 550, 100, 40);
        getContentPane().add(kontak_pegawai_hadi);
        kontak_pegawai_hadi.setBounds(160, 480, 270, 40);

        tabel_hadi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_hadi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_hadiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_hadi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 680, 710, 170);

        alamat_hadi.setColumns(20);
        alamat_hadi.setRows(5);
        jScrollPane2.setViewportView(alamat_hadi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 310, 270, 96);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 80);

        setSize(new java.awt.Dimension(775, 937));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void getdata(){
        // Code Tampil Data
       DefaultTableModel tbm = new DefaultTableModel();
               //membuat nama kolom pada tabel
                  tbm.addColumn("id_pegawai");
                  tbm.addColumn("nama_pegawai");
                  tbm.addColumn("jenis_kelamin");
                  tbm.addColumn("alamat_pegawai");
                  tbm.addColumn("Bagian");
                  tbm.addColumn("kontak_pegawai");
                tabel_hadi.setModel(tbm);              
      db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbpegawai_hadi";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
             
            while (rs.next()) {               
              tbm.addRow(new Object[]{
                rs.getString("id_pegawai"),
                rs.getString("nama_pegawai"),
                rs.getString("jenis_kelamin"),
                rs.getString("alamat_pegawai"),
                rs.getString("Bagian"),
                rs.getString("kontak_pegawai"),
            });
               tabel_hadi.setModel(tbm);
          }            
        } catch (SQLException e)
        {      
    }
 }
     public void textblank()
     {
         id_pegawai_hadi.setText("");
         nama_pegawai_hadi.setText("");
         alamat_hadi.setText("");
         bagian_hadi.setText("");
         kontak_pegawai_hadi.setText("");
         
     }
    private void tabel_hadiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_hadiMouseClicked

        // TODO add your handling code here:
        db.koneksiDatabase();
        String jekel;
        boolean result = false;
        if(pria_hadi.isSelected()){
            jekel = "Pria";
        }else{
            jekel = "Wanita";
        }

        databaru = false; // menampilkan data ke textboxt
        try {
            int row =tabel_hadi.getSelectedRow();
            String tabel_klik=(tabel_hadi.getModel().getValueAt(row, 0).toString());
            db.koneksiDatabase();
            String query = "SELECT * FROM tbpegawai_hadi where id_pegawai = '" + tabel_klik + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                id_pegawai_hadi.setText(rs.getString("id_pegawai"));
                nama_pegawai_hadi.setText(rs.getString("nama_pegawai"));
                if(rs.getString("jenis_kelamin").equals("Pria")){
                    pria_hadi.setSelected(true);
                }else{
                    wanita_hadi.setSelected(true);
                }
                alamat_hadi.setText(rs.getString("alamat_pegawai"));
                bagian_hadi.setText(rs.getString("Bagian"));
                kontak_pegawai_hadi.setText(rs.getString("Kontak_Pegawai"));
            }
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_tabel_hadiMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        textblank();
        id_pegawai_hadi.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         // Simpan Data
        db.koneksiDatabase();
        String jekel;
        boolean result = false;
        if(pria_hadi.isSelected()){
            jekel = "Pria";
    }else{
            jekel = "Wanita";
}

        // kode Simpan---------------
        String sql = "Insert Into tbpegawai_hadi Values ('" + id_pegawai_hadi.getText() +
        "',  '" + nama_pegawai_hadi.getText() +
        "','" + jekel +
        "','" + alamat_hadi.getText() +
        "','" + bagian_hadi.getText() +
        "','" + kontak_pegawai_hadi.getText() +
        "')";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Simpan Sukses !");
            
            textblank();
            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         db.koneksiDatabase();
          boolean result = false;
          String jekel="";
          
          if(pria_hadi.isSelected()){
              jekel="Pria";
          }else{
              jekel="Wanita";
          }
    
        
        try {
            String sql = "update tbpegawai_hadi SET id_pegawai ='"+ id_pegawai_hadi.getText()+
                 "',nama_pegawai = '" + nama_pegawai_hadi.getText()+
                "',jenis_kelamin = '"+jekel+
                "',alamat_pegawai = '" + alamat_hadi.getText()+
                 "',Bagian = '" + bagian_hadi.getText()+
                 "',kontak_pegawai = '" + kontak_pegawai_hadi.getText()+
                 "' WHERE id_pegawai = '"+id_pegawai_hadi.getText()+
                "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            textblank();
            getdata();
            
          } catch (SQLException e)
             {     
                  JOptionPane.showMessageDialog(null, e.getMessage());              
             }

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM tbpegawai_hadi where id_pegawai  = '" + id_pegawai_hadi.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                //   tekskosong();
                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        textblank();
        id_pegawai_hadi.requestFocus();
    }//GEN-LAST:event_cancelActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
  
        //Cari
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbpegawai_hadi where id_pegawai = '" + cari_hadi.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                id_pegawai_hadi.setText(rs.getString("id_pegawai"));
                nama_pegawai_hadi.setText(rs.getString("nama_pegawai"));
                if(rs.getString("jenis_kelamin").equals("Pria")){
                pria_hadi.setSelected(true);
            }else{
                wanita_hadi.setSelected(true);
            }
                alamat_hadi.setText(rs.getString("alamat_pegawai"));
                bagian_hadi.setText(rs.getString("bagian"));
                kontak_pegawai_hadi.setText(rs.getString("kontak_pegawai"));
            }
       }
     catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formpegawai_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formpegawai_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formpegawai_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formpegawai_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formpegawai_hadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea alamat_hadi;
    private javax.swing.JTextField bagian_hadi;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cari_hadi;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JTextField id_pegawai_hadi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jekel;
    private javax.swing.JTextField kontak_pegawai_hadi;
    private javax.swing.JTextField nama_pegawai_hadi;
    private javax.swing.JRadioButton pria_hadi;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabel_hadi;
    private javax.swing.JButton update;
    private javax.swing.JRadioButton wanita_hadi;
    // End of variables declaration//GEN-END:variables
}
