/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket_hadi;
import java.awt.HeadlessException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi_hadi;

/**
 *
 * @author admin
 */
public class Formsupplier_hadi extends javax.swing.JFrame {
    private Connection koneksi;
    private koneksi_hadi db=new koneksi_hadi();    
    public boolean databaru;
    private boolean result;

    /**
     * Creates new form Formsupplier_hadi
     */
    public Formsupplier_hadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kodesupplier_hadi = new javax.swing.JTextField();
        namasupplier_hadi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatsupplier_hadi = new javax.swing.JTextArea();
        kontaksupplier_hadi = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        search = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        cari_hadi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_hadi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 2, 36)); // NOI18N
        jLabel1.setText("FORM SUPPLIER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 130);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Kontak Supplier");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 450, 140, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Kode Supplier");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 140, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nama Supplier");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 140, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Alamat Supplier");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 340, 140, 30);
        getContentPane().add(kodesupplier_hadi);
        kodesupplier_hadi.setBounds(150, 160, 270, 40);
        getContentPane().add(namasupplier_hadi);
        namasupplier_hadi.setBounds(150, 250, 270, 40);

        alamatsupplier_hadi.setColumns(20);
        alamatsupplier_hadi.setRows(5);
        jScrollPane1.setViewportView(alamatsupplier_hadi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 320, 270, 96);
        getContentPane().add(kontaksupplier_hadi);
        kontaksupplier_hadi.setBounds(150, 450, 280, 30);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(590, 510, 110, 40);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seaRch.png"))); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(20, 560, 120, 40);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(120, 510, 100, 40);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(230, 510, 110, 40);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(350, 510, 110, 40);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(470, 510, 110, 40);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(20, 510, 90, 40);
        getContentPane().add(cari_hadi);
        cari_hadi.setBounds(150, 560, 150, 40);

        tabel_hadi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_hadi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_hadiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_hadi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 630, 720, 110);

        setSize(new java.awt.Dimension(782, 846));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //----------------------------Menampilkan Data Ke Tabel -----------
     public void getdata(){
        // Code Tampil Data
       DefaultTableModel tbm = new DefaultTableModel();
               //membuat nama kolom pada tabel
                  tbm.addColumn("Kode Supplier");
                  tbm.addColumn("Nama Supplier");
                  tbm.addColumn("Alamat Supplier");
                  tbm.addColumn("Kontak Supplier");
                tabel_hadi.setModel(tbm);              
      db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbsupplier_hadi";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
             
            while (rs.next()) {               
              tbm.addRow(new Object[]{
                rs.getString("kode_supplier"),
                rs.getString("nama_supplier"),
                rs.getString("alamat_supplier"),
                rs.getString("kontak_supplier"),
            });
               tabel_hadi.setModel(tbm);
          }            
        } catch (SQLException e)
        {      
    }
 }
     public void textblank()
     {
         kodesupplier_hadi.setText("");
         namasupplier_hadi.setText("");
         alamatsupplier_hadi.setText("");
         kontaksupplier_hadi.setText("");
         
     }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        textblank();
        kodesupplier_hadi.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
          // Simpan Data
        db.koneksiDatabase();
        boolean result = false;

        // kode Simpan---------------
        String sql = "Insert Into tbsupplier_hadi Values ('" + kodesupplier_hadi.getText() +
        "','" + namasupplier_hadi.getText() +
        "','" + alamatsupplier_hadi.getText() +
        "','" + kontaksupplier_hadi.getText() +
        "')";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Simpan Sukses !");
            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        db.koneksiDatabase();
          boolean result = false;
        
        try {
            String sql = "update tbsupplier_hadi SET kode_supplier ='"+ kodesupplier_hadi.getText()+
                 "',nama_supplier = '" + namasupplier_hadi.getText()+
                "',alamat_supplier = '" + alamatsupplier_hadi.getText()+
                 "',kontak_supplier = '" + kontaksupplier_hadi.getText()+
                 "' WHERE kode_supplier = '"+kodesupplier_hadi.getText()+
                "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            textblank();
            getdata();
            
          } catch (SQLException e)
             {     
                  JOptionPane.showMessageDialog(null, e.getMessage());              
             }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         // Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM tbsupplier_hadi where kode_supplier  = '" + kodesupplier_hadi.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                //   tekskosong();
                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        textblank();
        kodesupplier_hadi.requestFocus();
    }//GEN-LAST:event_cancelActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        // Cari Data
        db.koneksiDatabase();
        boolean result = false;

        try {
            String query = "SELECT * FROM tbsupplier_hadi where kode_supplier = '" + cari_hadi.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                kodesupplier_hadi.setText(rs.getString("kode_supplier"));
                namasupplier_hadi.setText(rs.getString("nama_supplier"));
                alamatsupplier_hadi.setText(rs.getString("alamat_supplier"));
                kontaksupplier_hadi.setText(rs.getString("kontak_supplier"));
                

            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");

        }
       
    }//GEN-LAST:event_searchActionPerformed

    private void tabel_hadiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_hadiMouseClicked

        // TODO add your handling code here:
        boolean result = false;

        databaru = false; // menampilkan data ke textboxt
        try {
            int row =tabel_hadi.getSelectedRow();
            String tabel_klik=(tabel_hadi.getModel().getValueAt(row, 0).toString());
            db.koneksiDatabase();
            String query = "SELECT * FROM tbsupplier_hadi where kode_supplier = '" + tabel_klik + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                kodesupplier_hadi.setText(rs.getString("kode_supplier"));
                namasupplier_hadi.setText(rs.getString("nama_supplier"));
                alamatsupplier_hadi.setText(rs.getString("alamat_supplier"));
                kontaksupplier_hadi.setText(rs.getString("kontak_supplier"));
               
            }
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_tabel_hadiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formsupplier_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formsupplier_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formsupplier_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formsupplier_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formsupplier_hadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea alamatsupplier_hadi;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cari_hadi;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodesupplier_hadi;
    private javax.swing.JTextField kontaksupplier_hadi;
    private javax.swing.JTextField namasupplier_hadi;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabel_hadi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
