/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket_hadi;
   import java.sql.Connection;
   import java.sql.ResultSet;
   import java.sql.SQLException;
   import java.sql.Statement;
   import javax.swing.JOptionPane;
   import javax.swing.table.DefaultTableModel;
   import java.text.SimpleDateFormat;
   import java.sql.PreparedStatement;
   import java.util.ArrayList;
   import java.util.List;
import koneksi.koneksi_hadi;

/**
 *
 * @author admin
 */
public class FormTransaksiPenjualan_hadi extends javax.swing.JFrame {
    private Connection koneksi;
    private koneksi_hadi db = new koneksi_hadi();
    private PreparedStatement pst;
    public boolean databaru;
    private String sqldetail;

    /**
     * Creates new form FormTransaksiPenjualan_hadi
     */
    public FormTransaksiPenjualan_hadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggal_hadi = new com.toedter.calendar.JDateChooser();
        nofaktur_hadi = new javax.swing.JTextField();
        kode_pegawaihadi = new javax.swing.JComboBox<>();
        namabarang_hadi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cari_hadi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kodebarang_hadi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pegawai_hadi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        harga_hadi = new javax.swing.JTextField();
        jumlah_hadi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_hadi = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        gtotal_hadi = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI PENJUALAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(287, 11, 250, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("NO FAKTUR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 55, 68, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("TANGGAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(16, 111, 55, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("PEGAWAI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(16, 160, 80, 15);
        getContentPane().add(tanggal_hadi);
        tanggal_hadi.setBounds(112, 102, 138, 32);
        getContentPane().add(nofaktur_hadi);
        nofaktur_hadi.setBounds(112, 46, 191, 33);

        kode_pegawaihadi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kode_pegawaihadiItemStateChanged(evt);
            }
        });
        getContentPane().add(kode_pegawaihadi);
        kode_pegawaihadi.setBounds(112, 153, 138, 28);
        getContentPane().add(namabarang_hadi);
        namabarang_hadi.setBounds(193, 254, 147, 28);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(401, 51, 100, 25);
        getContentPane().add(cari_hadi);
        cari_hadi.setBounds(520, 50, 154, 33);

        jLabel5.setText("KODE BARANG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(34, 226, 90, 16);

        kodebarang_hadi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kodebarang_hadiItemStateChanged(evt);
            }
        });
        getContentPane().add(kodebarang_hadi);
        kodebarang_hadi.setBounds(16, 254, 128, 28);

        jLabel6.setText("NAMA BARANG");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(231, 226, 85, 16);
        getContentPane().add(pegawai_hadi);
        pegawai_hadi.setBounds(290, 150, 191, 28);

        jLabel7.setText("HARGA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(411, 226, 70, 16);
        getContentPane().add(harga_hadi);
        harga_hadi.setBounds(358, 254, 147, 28);
        getContentPane().add(jumlah_hadi);
        jumlah_hadi.setBounds(523, 254, 147, 28);

        jLabel8.setText("JUMLAH");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(576, 226, 80, 16);

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(698, 251, 100, 35);

        tabel_hadi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabel_hadi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 320, 730, 120);

        jLabel9.setText("GRAND TOTAL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 480, 90, 16);
        getContentPane().add(gtotal_hadi);
        gtotal_hadi.setBounds(120, 470, 160, 30);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(20, 530, 90, 39);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(120, 530, 100, 39);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(230, 530, 130, 39);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(370, 530, 110, 39);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(490, 530, 120, 39);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(620, 530, 110, 39);

        jLabel10.setFont(new java.awt.Font("Agency FB", 2, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cpright.png"))); // NOI18N
        jLabel10.setText("Muhamad Hadi Saputra - 021200015");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 660, 230, 48);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 40);

        setSize(new java.awt.Dimension(824, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void getdata(){
        // Code Tampil Data
        DefaultTableModel tbm = new DefaultTableModel();
        //membuat nama kolom pada tabel
            tbm.addColumn("Kode Barang");
            tbm.addColumn("Nama Barang");
            tbm.addColumn("Harga");
            tbm.addColumn("Jumlah");
            tbm.addColumn("Total");
            tabel_hadi.setModel(tbm);
            db.koneksiDatabase();

               
    } 
            public void textblank()
            {
                nofaktur_hadi.setText("");
                tanggal_hadi.setDate(null);
                kodebarang_hadi.setSelectedIndex(0);
                namabarang_hadi.setText("");
                kode_pegawaihadi.setSelectedIndex(0);
                pegawai_hadi.setText("");
                harga_hadi.setText("");
                jumlah_hadi.setText("");
                gtotal_hadi.setText("");
                cari_hadi.setText("");
            } 
            
            
            
            // Procedure Menampilkan Data Ke Combo Box        
   
  
              
    public void tampil_ID_2(){
              
         try
          {
            String query = "SELECT * FROM tbpegawai_hadi group by id_pegawai";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            kode_pegawaihadi.addItem("Pilih Data Pegawai");
            while (rs.next()) 
              {                       
               kode_pegawaihadi.addItem(rs.getString("id_pegawai"));
              
             }
          }   
         
        catch(Exception ex)
        {     
        } 
    }
    
    public void tampil_ID_3(){
              
         try
          {
            String query = "SELECT * FROM tbbarang_hadi group by kode_barang";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            kodebarang_hadi.addItem(" Pilih Data Barang");
            while (rs.next()) 
              {                       
               kodebarang_hadi.addItem(rs.getString("kode_barang"));
              
             }
          }   
         
        catch(Exception ex)
        {     
        } 
    }
    
    
void  simpan()
    {
      int a = 0;
          sqldetail = "INSERT INTO tbdetail_penjualanhadi "+
                   "VALUES"+
                          "('"+nofaktur_hadi.getText() +"', "+
                          "'"+ tabel_hadi.getValueAt(a,0).toString() +"', "+
                          "'"+tabel_hadi.getValueAt(a,2).toString() +"', "+
                          "'"+tabel_hadi.getValueAt(a,3).toString() +"' )";
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        nofaktur_hadi.setText("");
        tanggal_hadi.setDate(null);
        kodebarang_hadi.setSelectedIndex(0);
        namabarang_hadi.setText("");
        kode_pegawaihadi.setSelectedIndex(0);
        pegawai_hadi.setText("");
        harga_hadi.setText("");
        jumlah_hadi.setText("");
        gtotal_hadi.setText("");
        cari_hadi.setText("");
     
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
 // Simpan Data Header Service

        db.koneksiDatabase();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String kode_supplier, idpegawai_hadi, kode_barang ;
        idpegawai_hadi= (String) kode_pegawaihadi.getSelectedItem();
        boolean result = false;
        boolean resultdetail = false;

        // kode Simpan---------------
        String sql = "Insert Into header_penjualanhadi Values ('" + nofaktur_hadi.getText() + "',  '" +
        sdf.format(tanggal_hadi.getDate()) + "','" +
        idpegawai_hadi + "','" +
        gtotal_hadi.getText() + "' )";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;

            // Akhir Proses Simpan Header.......

            // Proses Simpan Detail

            int rows=tabel_hadi.getRowCount();
            String queryco = "Insert into detail_penjualanhadi(no_nota,kode_barang,harga_penjualan,jumlah_penjualan) values (?,?,?,?)";
            pst = db.getKoneksi().prepareStatement(queryco);
            db.getKoneksi().setAutoCommit(false);
            for(int row = 0; row<rows; row++)
            {
                String nofaktur = (String)nofaktur_hadi.getText();
                String kodebarang = (String) tabel_hadi.getValueAt(row, 0);
                float harga = Float.parseFloat(tabel_hadi.getValueAt(row, 2).toString());
                int jumlah = Integer.parseInt(tabel_hadi.getValueAt(row, 3).toString());
                pst.setString(1, nofaktur);
                pst.setString(2, kodebarang);
                pst.setFloat(3, harga);
                pst.setInt(4, jumlah);
                pst.addBatch();
            }
            pst.executeBatch();
            db.getKoneksi().commit();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            //simpan();

            textblank();

        }catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }       
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        db.koneksiDatabase();
          boolean result = false;
        
        try {
            String sql = "update detail_penjualanhadi SET no_faktur ='"+ nofaktur_hadi.getText()+
                 "',id_pegawai = '" + pegawai_hadi.getText()+
                 "' WHERE no_faktur = '"+nofaktur_hadi.getText()+
                "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            textblank();
            getdata();
            
          } catch (SQLException e)
             {     
                  JOptionPane.showMessageDialog(null, e.getMessage());              
             }
       
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
// Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM detail_penjualanhadi where no_faktur  = '" + nofaktur_hadi.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                //   tekskosong();
                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
     //CANCEL
     textblank();  
    }//GEN-LAST:event_cancelActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        getdata();
        tampil_ID_2();
        tampil_ID_3();
  
    }//GEN-LAST:event_formWindowOpened

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
         int jumlah;
        double harga, total;
        jumlah=Integer.parseInt(jumlah_hadi.getText());
        harga=Double.parseDouble(harga_hadi.getText());
        total=harga*jumlah;
        //Memasukkan data ke tabel
        DefaultTableModel dataModel = (DefaultTableModel) tabel_hadi.getModel();
        List list = new ArrayList<>();
        tabel_hadi.setAutoCreateColumnsFromModel(true);
        list.add(kodebarang_hadi.getSelectedItem());
        list.add(namabarang_hadi.getText());
        list.add(harga_hadi.getText());
        list.add(jumlah_hadi.getText());
        list.add(total);
        dataModel.addRow(list.toArray());
        //----------Kosongkan Field
        kodebarang_hadi.setSelectedIndex(0);
        namabarang_hadi.setText("");
        harga_hadi.setText("");
        jumlah_hadi.setText("");

        double total_hitung = 0;
        for (int i = 0; i < tabel_hadi.getRowCount(); i++){
            double amount = Double.parseDouble(tabel_hadi.getValueAt(i, 4).toString());
            total_hitung += amount;
        }
        gtotal_hadi.setText(String.valueOf(total_hitung));
    }//GEN-LAST:event_tambahActionPerformed

    private void kodebarang_hadiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kodebarang_hadiItemStateChanged
        // TODO add your handling code here:
        String id;
        id=(String)kodebarang_hadi.getSelectedItem();
        namabarang_hadi.setText(id);
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbbarang_hadi where kode_barang= '" + id + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                namabarang_hadi.setText(rs.getString("nama_barang"));
                harga_hadi.setText(rs.getString("harga_jual"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_kodebarang_hadiItemStateChanged

    private void kode_pegawaihadiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kode_pegawaihadiItemStateChanged
        // TODO add your handling code here:
         String id;
        id=(String)kode_pegawaihadi.getSelectedItem();
        pegawai_hadi.setText(id);
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbpegawai_hadi where id_pegawai= '" + id + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                pegawai_hadi.setText(rs.getString("nama_pegawai"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_kode_pegawaihadiItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        db.koneksiDatabase();
        boolean result = false;

        try {
            String query = "SELECT * FROM detail_penjualanhadi where no_faktur = '" + cari_hadi.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                nofaktur_hadi.setText(rs.getString("no_faktur"));
                pegawai_hadi.setText(rs.getString("id_pegawai"));
                jumlah_hadi.setText(rs.getString("total"));
               

            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiPenjualan_hadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cari_hadi;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gtotal_hadi;
    private javax.swing.JTextField harga_hadi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_hadi;
    private javax.swing.JComboBox<String> kode_pegawaihadi;
    private javax.swing.JComboBox<String> kodebarang_hadi;
    private javax.swing.JTextField namabarang_hadi;
    private javax.swing.JTextField nofaktur_hadi;
    private javax.swing.JTextField pegawai_hadi;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_hadi;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggal_hadi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
