/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket_hadi;
import java.awt.HeadlessException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi_hadi;

/**
 *
 * @author admin
 */
public class Formbarang_hadi extends javax.swing.JFrame {
    private Connection koneksi;
    private koneksi_hadi db=new koneksi_hadi();    
    public boolean databaru;
    private boolean result;

    /**
     * Creates new form Formbarang_hadi
     */
    public Formbarang_hadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jumlah_hadi = new javax.swing.JTextField();
        kode_barang_hadi = new javax.swing.JTextField();
        nama_barang_hadi = new javax.swing.JTextField();
        harga_beli_hadi = new javax.swing.JTextField();
        cari_hadi = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        search = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        harga_jual_hadi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_hadi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        jLabel1.setText("FORM BARANG");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barang.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 110);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("JUMLAH");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 430, 140, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("KODE BARANG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 140, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("NAMA BARANG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 140, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("HARGA BELI");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 310, 140, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("HARGA JUAL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 370, 140, 17);
        getContentPane().add(jumlah_hadi);
        jumlah_hadi.setBounds(200, 420, 80, 40);
        getContentPane().add(kode_barang_hadi);
        kode_barang_hadi.setBounds(200, 170, 220, 40);
        getContentPane().add(nama_barang_hadi);
        nama_barang_hadi.setBounds(200, 240, 320, 40);
        getContentPane().add(harga_beli_hadi);
        harga_beli_hadi.setBounds(200, 300, 230, 40);
        getContentPane().add(cari_hadi);
        cari_hadi.setBounds(190, 560, 230, 40);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(700, 490, 100, 40);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seaRch.png"))); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(50, 560, 120, 40);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(170, 490, 100, 40);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(290, 490, 110, 40);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(420, 490, 120, 40);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(560, 490, 120, 40);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(50, 490, 100, 40);
        getContentPane().add(harga_jual_hadi);
        harga_jual_hadi.setBounds(200, 360, 230, 40);

        tabel_hadi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_hadi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_hadiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_hadi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 620, 880, 150);

        setSize(new java.awt.Dimension(981, 870));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         textblank();
         kode_barang_hadi.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        // Simpan Data
        db.koneksiDatabase();
        boolean result = false;

        // kode Simpan---------------
        String sql = "Insert Into tbbarang_hadi Values ('" + kode_barang_hadi.getText() +
                                                                "',  '" + nama_barang_hadi.getText() +
                                                                "','"   +   harga_beli_hadi.getText() +
                                                                 "','"  +  harga_jual_hadi.getText() +
                                                                 "','"  +  jumlah_hadi.getText() +
                                                                 "')";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Simpan Sukses !");
            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       db.koneksiDatabase();
        boolean result = false;

        // kode dibawah ini dibuat satu baris saja---------------

        String sql = "update tbbarang_hadi SET kode_barang = '"+kode_barang_hadi.getText()
        +"', nama_barang = '"+nama_barang_hadi.getText()
        +"', harga_beli = '"+harga_beli_hadi.getText()
        +"', harga_jual = '"+harga_jual_hadi.getText()
        +"', jumlah = '"+jumlah_hadi.getText()
        +"' WHERE kode_barang = '"+kode_barang_hadi.getText()+"'";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            textblank();
            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
       

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        // Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM tbbarang_hadi where kode_barang  = '" + kode_barang_hadi.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                //   tekskosong();
                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        textblank();
        kode_barang_hadi.requestFocus();
    }//GEN-LAST:event_cancelActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        // Cari Data
        db.koneksiDatabase();
        boolean result = false;

        try {
            String query = "SELECT * FROM tbbarang_hadi where kode_barang = '" + cari_hadi.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                kode_barang_hadi.setText(rs.getString("kode_barang"));
                nama_barang_hadi.setText(rs.getString("nama_barang"));
                harga_beli_hadi.setText(rs.getString("harga_beli"));
                harga_jual_hadi.setText(rs.getString("harga_jual"));
                jumlah_hadi.setText(rs.getString("jumlah"));

            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");

        }
    }//GEN-LAST:event_searchActionPerformed

    private void tabel_hadiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_hadiMouseClicked

        // TODO add your handling code here:
        boolean result = false;

        databaru = false; // menampilkan data ke textboxt
        try {
            int row =tabel_hadi.getSelectedRow();
            String tabel_klik=(tabel_hadi.getModel().getValueAt(row, 0).toString());
            db.koneksiDatabase();
            String query = "SELECT * FROM tbbarang_hadi where kode_barang = '" + tabel_klik + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                kode_barang_hadi.setText(rs.getString("kode_barang"));
                nama_barang_hadi.setText(rs.getString("nama_barang"));
                harga_beli_hadi.setText(rs.getString("harga_beli"));
                harga_jual_hadi.setText(rs.getString("harga_jual"));
                jumlah_hadi.setText(rs.getString("jumlah"));
            }
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_tabel_hadiMouseClicked

    
    //----------------------------Menampilkan Data Ke Tabel -----------
     public void getdata(){
        // Code Tampil Data
       DefaultTableModel tbm = new DefaultTableModel();
               //membuat nama kolom pada tabel
                  tbm.addColumn("kode_barang");
                  tbm.addColumn("nama_barang");
                  tbm.addColumn("harga_beli");
                  tbm.addColumn("harga_jual");
                  tbm.addColumn("jumlah");
                tabel_hadi.setModel(tbm);              
      db.koneksiDatabase();
        try {
            String query = "SELECT * FROM tbbarang_hadi";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
             
            while (rs.next()) {               
              tbm.addRow(new Object[]{
                rs.getString("kode_barang"),
                rs.getString("nama_barang"),
                rs.getString("harga_beli"),
                rs.getString("harga_jual"),
                rs.getString("jumlah"),
            });
               tabel_hadi.setModel(tbm);
          }            
        } catch (SQLException e)
        {      
    }
 }
     public void textblank()
     {
         kode_barang_hadi.setText("");
         nama_barang_hadi.setText("");
         harga_beli_hadi.setText("");
         harga_jual_hadi.setText("");
         jumlah_hadi.setText("");
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formbarang_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formbarang_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formbarang_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formbarang_hadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formbarang_hadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cari_hadi;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JTextField harga_beli_hadi;
    private javax.swing.JTextField harga_jual_hadi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_hadi;
    private javax.swing.JTextField kode_barang_hadi;
    private javax.swing.JTextField nama_barang_hadi;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabel_hadi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
